name: Docker Build

on:
  push:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Build Docker image
        run: docker build -t tamerlanchik/solar${GITHUB_REF##*/}:${GITHUB_SHA::8} .
      - name: Push the image
        run: docker push tamerlanchik/solar${GITHUB_REF##*/}:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull 'tamerlanchik/solar${GITHUB_REF##*/}:${GITHUB_SHA::8}'
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker run -d -p 8080:8080 tamerlanchik/solar${GITHUB_REF##*/}:${GITHUB_SHA::8}